blank_issues_enabled: false
contact_links:
  - name: Questions and usage help
    url: https://github.com/http418imateapot/homeassistant-mqtt-blueprints/discussions
    about: Please use GitHub Discussions for questions.
